image: busybox

pages:
  stage: deploy
  script:
  - mkdir public
  - cp -r assets public/assets
  - cp *html *css public/
  artifacts:
    paths:
    - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
